export const INDUSTRIES: string[] = [
	"3D Printing",
	"3D Technology",
	"A/B Testing",
	"Accounting",
	"Ad Exchange",
	"Ad Network",
	"Ad Retargeting",
	"Ad Server",
	"Ad Targeting",
	"Adult",
	"Advanced Materials",
	"Adventure Travel",
	"Advertising Platforms",
	"Advertising",
	"Advice",
	"Aerospace",
	"Affiliate Marketing",
	"Agriculture",
	"AgTech",
	"Air Transportation",
	"Alternative Medicine",
	"Alumni",
	"American Football",
	"Amusement Park and Arcade",
	"Analytics",
	"Android",
	"Angel Investment",
	"Animal Feed",
	"Animation",
	"App Discovery",
	"App Marketing",
	"Application Performance Management",
	"Application Specific Integrated Circuit (ASIC)",
	"Apps",
	"Aquaculture",
	"Architecture",
	"Archiving Service",
	"Art",
	"Artificial Intelligence",
	"Asset Management",
	"Assisted Living",
	"Assistive Technology",
	"Association",
	"Auctions",
	"Audio",
	"Audiobooks",
	"Augmented Reality",
	"Auto Insurance",
	"Automotive",
	"Autonomous Vehicles",
	"B2B",
	"B2C",
	"Baby",
	"Bakery",
	"Banking",
	"Baseball",
	"Basketball",
	"Battery",
	"Beauty",
	"Big Data",
	"Billing",
	"Biofuel",
	"Bioinformatics",
	"Biomass Energy",
	"Biometrics",
	"Biopharma",
	"Biotechnology",
	"Bitcoin",
	"Blockchain",
	"Blogging Platforms",
	"Boating",
	"Brand Marketing",
	"Brewing",
	"Broadcasting",
	"Browser Extensions",
	"Building Maintenance",
	"Building Material",
	"Business Development",
	"Business Information Systems",
	"Business Intelligence",
	"Business Travel",
	"CAD",
	"Call Center",
	"Cannabis",
	"Car Sharing",
	"Career Planning",
	"Casino",
	"Casual Games",
	"Catering",
	"Cause Marketing",
	"Celebrity",
	"Charity",
	"Charter Schools",
	"Chemical Engineering",
	"Chemical",
	"Child Care",
	"Children",
	"CivicTech",
	"Civil Engineering",
	"Classifieds",
	"Clean Energy",
	"CleanTech",
	"Clinical Trials",
	"Cloud Computing",
	"Cloud Data Services",
	"Cloud Infrastructure",
	"Cloud Management",
	"Cloud Security",
	"Cloud Storage",
	"CMS",
	"Coffee",
	"Collaboration",
	"Collaborative Consumption",
	"Collectibles",
	"Collection Agency",
	"College Recruiting",
	"Comics",
	"Commercial Insurance",
	"Commercial Lending",
	"Commercial Real Estate",
	"Commercial",
	"Communication Hardware",
	"Communications Infrastructure",
	"Communities",
	"Compliance",
	"Computer Vision",
	"Computer",
	"Concerts",
	"Confectionery",
	"Console Games",
	"Construction",
	"Consulting",
	"Consumer Applications",
	"Consumer Electronics",
	"Consumer Goods",
	"Consumer Lending",
	"Consumer Research",
	"Consumer Reviews",
	"Consumer Software",
	"Consumer",
	"Contact Management",
	"Content Creators",
	"Content Delivery Network",
	"Content Discovery",
	"Content Marketing",
	"Content Syndication",
	"Content",
	"Contests",
	"Continuing Education",
	"Cooking",
	"Corporate Training",
	"Corrections Facilities",
	"Cosmetic Surgery",
	"Cosmetics",
	"Coupons",
	"Courier Service",
	"Coworking",
	"Craft Beer",
	"Creative Agency",
	"Credit Bureau",
	"Credit Cards",
	"Credit",
	"Cricket",
	"CRM",
	"Crowdfunding",
	"Crowdsourcing",
	"Cryptocurrency",
	"Customer Service",
	"Cyber Security",
	"Cycling",
	"Darknet",
	"Data Center Automation",
	"Data Center",
	"Data Integration",
	"Data Mining",
	"Data Storage",
	"Data Visualization",
	"Database",
	"Dating",
	"Debit Cards",
	"Debt Collections",
	"Delivery Service",
	"Delivery",
	"Dental",
	"Desktop Apps",
	"Developer APIs",
	"Developer Platform",
	"Developer Tools",
	"Diabetes",
	"Dietary Supplements",
	"Digital Entertainment",
	"Digital Marketing",
	"Digital Media",
	"Digital Signage",
	"Direct Marketing",
	"Direct Sales",
	"Distillery",
	"Diving",
	"DIY",
	"Document Management",
	"Document Preparation",
	"Domain Registrar",
	"DRM",
	"Drone Management",
	"Drones",
	"DSP",
	"E-Commerce Platforms",
	"E-Commerce",
	"E-Learning",
	"E-Signature",
	"EBooks",
	"Ediscovery",
	"EdTech",
	"Education",
	"Edutainment",
	"Elder Care",
	"Elderly",
	"Electric Vehicle",
	"Electrical Distribution",
	"Electronic Design Automation (EDA)",
	"Electronic Health Record (EHR)",
	"Electronics",
	"Email Marketing",
	"Email",
	"Embedded Software",
	"Embedded Systems",
	"Emergency Medicine",
	"Emerging Markets",
	"Employee Benefits",
	"Employment",
	"Energy Efficiency",
	"Energy Management",
	"Energy Storage",
	"Energy",
	"Enterprise Applications",
	"Enterprise Resource Planning (ERP)",
	"Enterprise Software",
	"Enterprise",
	"Environmental Consulting",
	"Environmental Engineering",
	"Equestrian",
	"eSports",
	"Ethereum",
	"Event Management",
	"Event Promotion",
	"Events",
	"Extermination Service",
	"Eyewear",
	"Facebook",
	"Facial Recognition",
	"Facilities Support Services",
	"Facility Management",
	"Family",
	"Fantasy Sports",
	"Farmers Market",
	"Farming",
	"Fashion",
	"Fast-Moving Consumer Goods",
	"Ferry Service",
	"Fertility",
	"Field Support",
	"Field-Programmable Gate Array (FPGA)",
	"File Sharing",
	"Film Distribution",
	"Film Production",
	"Film",
	"Finance",
	"Financial Exchanges",
	"Financial Services",
	"FinTech",
	"First Aid",
	"Fitness",
	"Flash Sale",
	"Flash Storage",
	"Fleet Management",
	"Flowers",
	"Food and Beverage",
	"Food Delivery",
	"Food Processing",
	"Food Trucks",
	"Forestry",
	"Fossil Fuels",
	"Foundries",
	"Franchise",
	"Fraud Detection",
	"Freelance",
	"Freemium",
	"Freight Service",
	"Fruit",
	"Fuel Cell",
	"Fuel",
	"Funding Platform",
	"Funerals",
	"Furniture",
	"Gambling",
	"Gamification",
	"Gaming",
	"Generation Y",
	"Generation Z",
	"Genetics",
	"Geospatial",
	"Gift Card",
	"Gift Exchange",
	"Gift Registry",
	"Gift",
	"Golf",
	"Google Glass",
	"Google",
	"Government",
	"GovTech",
	"GPS",
	"GPU",
	"Graphic Design",
	"Green Building",
	"Green Consumer Goods",
	"GreenTech",
	"Grocery",
	"Group Buying",
	"Guides",
	"Handmade",
	"Hardware",
	"Health Care",
	"Health Diagnostics",
	"Health Insurance",
	"Hedge Funds",
	"Higher Education",
	"Hockey",
	"Home and Garden",
	"Home Decor",
	"Home Health Care",
	"Home Improvement",
	"Home Renovation",
	"Home Services",
	"Homeland Security",
	"Homeless Shelter",
	"Horticulture",
	"Hospital",
	"Hospitality",
	"Hotel",
	"Housekeeping Service",
	"Human Computer Interaction",
	"Human Resources",
	"Humanitarian",
	"Hunting",
	"Hydroponics",
	"IaaS",
	"Identity Management",
	"Image Recognition",
	"Impact Investing",
	"In-Flight Entertainment",
	"Incubators",
	"Independent Music",
	"Indoor Positioning",
	"Industrial Automation",
	"Industrial Design",
	"Industrial Engineering",
	"Industrial Manufacturing",
	"Industrial",
	"Information and Communications Technology (ICT)",
	"Information Services",
	"Information Technology",
	"Infrastructure",
	"Innovation Management",
	"Insurance",
	"InsurTech",
	"Intellectual Property",
	"Intelligent Systems",
	"Interior Design",
	"Internet of Things",
	"Internet Radio",
	"Internet",
	"Intrusion Detection",
	"iOS",
	"ISP",
	"IT Infrastructure",
	"IT Management",
	"Janitorial Service",
	"Jewelry",
	"Journalism",
	"Knowledge Management",
	"Landscaping",
	"Language Learning",
	"Laser",
	"Last Mile Transportation",
	"Laundry and Dry-cleaning",
	"Law Enforcement",
	"Lead Generation",
	"Lead Management",
	"Leasing",
	"Legal Tech",
	"Legal",
	"Leisure",
	"Lending",
	"LGBT",
	"Life Insurance",
	"Life Science",
	"Lifestyle",
	"Lighting",
	"Limousine Service",
	"Lingerie",
	"Linux",
	"Livestock",
	"Local Advertising",
	"Local Business",
	"Local Shopping",
	"Local",
	"Location Based Services",
	"Logistics",
	"Loyalty Programs",
	"Machine Learning",
	"Machinery Manufacturing",
	"macOS",
	"Made to Order",
	"Management Consulting",
	"Management Information Systems",
	"Manufacturing",
	"Mapping Services",
	"Marine Technology",
	"Marine Transportation",
	"Market Research",
	"Marketing Automation",
	"Marketing",
	"Marketplace",
	"Mechanical Design",
	"Mechanical Engineering",
	"Media and Entertainment",
	"Medical Device",
	"Medical",
	"Meeting Software",
	"Men's",
	"Messaging",
	"mHealth",
	"Micro Lending",
	"Military",
	"Millennials",
	"Mineral",
	"Mining Technology",
	"Mining",
	"MMO Games",
	"Mobile Advertising",
	"Mobile Apps",
	"Mobile Devices",
	"Mobile Payments",
	"Mobile",
	"MOOC",
	"Motion Capture",
	"Multi-level Marketing",
	"Museums and Historical Sites",
	"Music Education",
	"Music Label",
	"Music Streaming",
	"Music Venues",
	"Music",
	"Musical Instruments",
	"Nanotechnology",
	"National Security",
	"Natural Language Processing",
	"Natural Resources",
	"Navigation",
	"Network Hardware",
	"Network Security",
	"Neuroscience",
	"News",
	"NFC",
	"Nightclubs",
	"Nightlife",
	"Nintendo",
	"Non Profit",
	"Nuclear",
	"Nursing and Residential Care",
	"Nutraceutical",
	"Nutrition",
	"Office Administration",
	"Oil and Gas",
	"Online Auctions",
	"Online Forums",
	"Online Games",
	"Online Portals",
	"Open Source",
	"Operating Systems",
	"Optical Communication",
	"Organic Food",
	"Organic",
	"Outdoor Advertising",
	"Outdoors",
	"Outpatient Care",
	"Outsourcing",
	"PaaS",
	"Packaging Services",
	"Paper Manufacturing",
	"Parenting",
	"Parking",
	"Parks",
	"Payments",
	"PC Games",
	"Peer to Peer",
	"Penetration Testing",
	"Performing Arts",
	"Personal Branding",
	"Personal Development",
	"Personal Finance",
	"Personal Health",
	"Personalization",
	"Pet",
	"Pharmaceutical",
	"Photo Editing",
	"Photo Sharing",
	"Photography",
	"Physical Security",
	"Plastics and Rubber Manufacturing",
	"Playstation",
	"Podcast",
	"Point of Sale",
	"Politics",
	"Pollution Control",
	"Ports and Harbors",
	"Power Grid",
	"Precious Metals",
	"Prediction Markets",
	"Predictive Analytics",
	"Presentation Software",
	"Presentations",
	"Price Comparison",
	"Primary Education",
	"Printing",
	"Privacy",
	"Private Cloud",
	"Private Social Networking",
	"Procurement",
	"Product Design",
	"Product Management",
	"Product Research",
	"Product Search",
	"Productivity Tools",
	"Professional Networking",
	"Professional Services",
	"Project Management",
	"Property Development",
	"Property Insurance",
	"Property Management",
	"Psychology",
	"Public Relations",
	"Public Safety",
	"Public Transportation",
	"Publishing",
	"Q&A",
	"QR Codes",
	"Quality Assurance",
	"Quantified Self",
	"Quantum Computing",
	"Racing",
	"Railroad",
	"Reading Apps",
	"Real Estate Investment",
	"Real Estate",
	"Real Time",
	"Recipes",
	"Recreation",
	"Recreational Vehicles",
	"Recruiting",
	"Recycling",
	"Rehabilitation",
	"Religion",
	"Renewable Energy",
	"Rental Property",
	"Rental",
	"Reputation",
	"Reservations",
	"Residential",
	"Resorts",
	"Restaurants",
	"Retail Technology",
	"Retail",
	"Retirement",
	"RFID",
	"Ride Sharing",
	"RISC",
	"Risk Management",
	"Robotics",
	"Rugby",
	"SaaS",
	"Sailing",
	"Sales Automation",
	"Sales",
	"Same Day Delivery",
	"Satellite Communication",
	"Scheduling",
	"Seafood",
	"Search Engine",
	"Secondary Education",
	"Security",
	"Self-Storage",
	"SEM",
	"Semantic Search",
	"Semantic Web",
	"Semiconductor",
	"Sensor",
	"SEO",
	"Serious Games",
	"Service Industry",
	"Sex Industry",
	"Sex Tech",
	"Sharing Economy",
	"Shipping Broker",
	"Shipping",
	"Shoes",
	"Shopping Mall",
	"Shopping",
	"Simulation",
	"Skiing",
	"Skill Assessment",
	"Small and Medium Businesses",
	"Smart Building",
	"Smart Cities",
	"Smart Home",
	"SMS",
	"Snack Food",
	"SNS",
	"Soccer",
	"Social Assistance",
	"Social Bookmarking",
	"Social CRM",
	"Social Entrepreneurship",
	"Social Impact",
	"Social Media Advertising",
	"Social Media Management",
	"Social Media Marketing",
	"Social Media",
	"Social Network",
	"Social News",
	"Social Recruiting",
	"Social Shopping",
	"Social",
	"Software Engineering",
	"Software",
	"Solar",
	"Space Travel",
	"Spam Filtering",
	"Speech Recognition",
	"Sponsorship",
	"Sporting Goods",
	"Sports",
	"Staffing Agency",
	"STEM Education",
	"Stock Exchanges",
	"Subscription Service",
	"Supply Chain Management",
	"Surfing",
	"Sustainability",
	"Swimming",
	"Table Tennis",
	"Task Management",
	"Taxi Service",
	"Tea",
	"Technical Support",
	"Teenagers",
	"Telecommunications",
	"Tennis",
	"Test and Measurement",
	"Text Analytics",
	"Textbook",
	"Textiles",
	"Theatre",
	"Therapeutics",
	"Ticketing",
	"Timber",
	"Timeshare",
	"Tobacco",
	"Tour Operator",
	"Tourism",
	"Toys",
	"Trade Shows",
	"Trading Platform",
	"Training",
	"Transaction Processing",
	"Translation Service",
	"Transportation",
	"Travel Accommodations",
	"Travel Agency",
	"Travel",
	"Tutoring",
	"TV Production",
	"TV",
	"Twitter",
	"Ultimate Frisbee",
	"Underserved Children",
	"Unified Communications",
	"Universities",
	"Usability Testing",
	"UX Design",
	"Vacation Rental",
	"Vending and Concessions",
	"Venture Capital",
	"Vertical Search",
	"Veterinary",
	"Video Advertising",
	"Video Chat",
	"Video Conferencing",
	"Video Editing",
	"Video Games",
	"Video on Demand",
	"Video Streaming",
	"Video",
	"Virtual Assistant",
	"Virtual Currency",
	"Virtual Desktop",
	"Virtual Goods",
	"Virtual Reality",
	"Virtual Workforce",
	"Virtual World",
	"Virtualization",
	"Visual Search",
	"Vocational Education",
	"VoIP",
	"Volley Ball",
	"Warehousing",
	"Waste Management",
	"Water Purification",
	"Water Transportation",
	"Water",
	"Wealth Management",
	"Wearables",
	"Web Apps",
	"Web Browsers",
	"Web Design",
	"Web Development",
	"Web Hosting",
	"WebOS",
	"Wedding",
	"Wellness",
	"Wholesale",
	"Wind Energy",
	"Windows Phone",
	"Windows",
	"Wine And Spirits",
	"Winery",
	"Wired Telecommunications",
	"Wireless",
	"Women's",
	"Wood Processing",
	"Xbox",
	"Young Adults",
];