export const COMPANY_INDUSTRIES: string[] = [
    "3D Printing",
    "3D Technology",
    "A/B Testing",
    "Accounting",
    "Ad Exchange",
    "Ad Network",
    "Ad Retargeting",
    "Ad Server",
    "Ad Targeting",
    "Adult",
    "Advanced Materials",
    "Adventure Travel",
    "Advertising",
    "Advertising Platforms",
    "Advice",
    "Aerospace",
    "Affiliate Marketing",
    "Agriculture",
    "AgTech",
    "Air Transportation",
    "Alternative Medicine",
    "Alumni",
    "American Football",
    "Amusement Park and Arcade",
    "Analytics",
    "Android",
    "Angel Investment",
    "Animal Feed",
    "Animation",
    "App Discovery",
    "App Marketing",
    "Application Performance Management",
    "Application Specific Integrated Circuit (ASIC)",
    "Apps",
    "Aquaculture",
    "Architecture",
    "Archiving Service",
    "Art",
    "Artificial Intelligence",
    "Asset Management",
    "Assisted Living",
    "Assistive Technology",
    "Association",
    "Auctions",
    "Audio",
    "Audiobooks",
    "Augmented Reality",
    "Auto Insurance",
    "Automotive",
    "Autonomous Vehicles",
    "B2B",
    "B2C",
    "Baby",
    "Bakery",
    "Banking",
    "Baseball",
    "Basketball",
    "Battery",
    "Beauty",
    "Big Data",
    "Billing",
    "Biofuel",
    "Bioinformatics",
    "Biomass Energy",
    "Biometrics",
    "Biopharma",
    "Biotechnology",
    "Bitcoin",
    "Blockchain",
    "Blogging Platforms",
    "Boating",
    "Brand Marketing",
    "Brewing",
    "Broadcasting",
    "Browser Extensions",
    "Building Maintenance",
    "Building Material",
    "Business Development",
    "Business Information Systems",
    "Business Intelligence",
    "Business Travel",
    "CAD",
    "Call Center",
    "Cannabis",
    "Car Sharing",
    "Career Planning",
    "Casino",
    "Casual Games",
    "Catering",
    "Cause Marketing",
    "Celebrity",
    "Charity",
    "Charter Schools",
    "Chemical",
    "Chemical Engineering",
    "Child Care",
    "Children",
    "CivicTech",
    "Civil Engineering",
    "Classifieds",
    "Clean Energy",
    "CleanTech",
    "Clinical Trials",
    "Cloud Computing",
    "Cloud Data Services",
    "Cloud Infrastructure",
    "Cloud Management",
    "Cloud Security",
    "Cloud Storage",
    "CMS",
    "Coffee",
    "Collaboration",
    "Collaborative Consumption",
    "Collectibles",
    "Collection Agency",
    "College Recruiting",
    "Comics",
    "Commercial",
    "Commercial Insurance",
    "Commercial Lending",
    "Commercial Real Estate",
    "Communication Hardware",
    "Communications Infrastructure",
    "Communities",
    "Compliance",
    "Computer",
    "Computer Vision",
    "Concerts",
    "Confectionery",
    "Console Games",
    "Construction",
    "Consulting",
    "Consumer",
    "Consumer Applications",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Lending",
    "Consumer Research",
    "Consumer Reviews",
    "Consumer Software",
    "Contact Management",
    "Content",
    "Content Creators",
    "Content Delivery Network",
    "Content Discovery",
    "Content Marketing",
    "Content Syndication",
    "Contests",
    "Continuing Education",
    "Cooking",
    "Corporate Training",
    "Corrections Facilities",
    "Cosmetic Surgery",
    "Cosmetics",
    "Coupons",
    "Courier Service",
    "Coworking",
    "Craft Beer",
    "Creative Agency",
    "Credit",
    "Credit Bureau",
    "Credit Cards",
    "Cricket",
    "CRM",
    "Crowdfunding",
    "Crowdsourcing",
    "Cryptocurrency",
    "Customer Service",
    "Cyber Security",
    "Cycling",
    "Darknet",
    "Data Center",
    "Data Center Automation",
    "Data Integration",
    "Data Mining",
    "Data Storage",
    "Data Visualization",
    "Database",
    "Dating",
    "Debit Cards",
    "Debt Collections",
    "Delivery",
    "Delivery Service",
    "Dental",
    "Desktop Apps",
    "Developer APIs",
    "Developer Platform",
    "Developer Tools",
    "Diabetes",
    "Dietary Supplements",
    "Digital Entertainment",
    "Digital Marketing",
    "Digital Media",
    "Digital Signage",
    "Direct Marketing",
    "Direct Sales",
    "Distillery",
    "Diving",
    "DIY",
    "Document Management",
    "Document Preparation",
    "Domain Registrar",
    "DRM",
    "Drone Management",
    "Drones",
    "DSP",
    "E-Commerce",
    "E-Commerce Platforms",
    "E-Learning",
    "E-Signature",
    "EBooks",
    "Ediscovery",
    "EdTech",
    "Education",
    "Edutainment",
    "Elder Care",
    "Elderly",
    "Electric Vehicle",
    "Electrical Distribution",
    "Electronic Design Automation (EDA)",
    "Electronic Health Record (EHR)",
    "Electronics",
    "Email",
    "Email Marketing",
    "Embedded Software",
    "Embedded Systems",
    "Emergency Medicine",
    "Emerging Markets",
    "Employee Benefits",
    "Employment",
    "Energy",
    "Energy Efficiency",
    "Energy Management",
    "Energy Storage",
    "Enterprise",
    "Enterprise Applications",
    "Enterprise Resource Planning (ERP)",
    "Enterprise Software",
    "Environmental Consulting",
    "Environmental Engineering",
    "Equestrian",
    "eSports",
    "Ethereum",
    "Event Management",
    "Event Promotion",
    "Events",
    "Extermination Service",
    "Eyewear",
    "Facebook",
    "Facial Recognition",
    "Facilities Support Services",
    "Facility Management",
    "Family",
    "Fantasy Sports",
    "Farmers Market",
    "Farming",
    "Fashion",
    "Fast-Moving Consumer Goods",
    "Ferry Service",
    "Fertility",
    "Field Support",
    "Field-Programmable Gate Array (FPGA)",
    "File Sharing",
    "Film",
    "Film Distribution",
    "Film Production",
    "Finance",
    "Financial Exchanges",
    "Financial Services",
    "FinTech",
    "First Aid",
    "Fitness",
    "Flash Sale",
    "Flash Storage",
    "Fleet Management",
    "Flowers",
    "Food and Beverage",
    "Food Delivery",
    "Food Processing",
    "Food Trucks",
    "Forestry",
    "Fossil Fuels",
    "Foundries",
    "Franchise",
    "Fraud Detection",
    "Freelance",
    "Freemium",
    "Freight Service",
    "Fruit",
    "Fuel",
    "Fuel Cell",
    "Funding Platform",
    "Funerals",
    "Furniture",
    "Gambling",
    "Gamification",
    "Gaming",
    "Generation Y",
    "Generation Z",
    "Genetics",
    "Geospatial",
    "Gift",
    "Gift Card",
    "Gift Exchange",
    "Gift Registry",
    "Golf",
    "Google",
    "Google Glass",
    "Government",
    "GovTech",
    "GPS",
    "GPU",
    "Graphic Design",
    "Green Building",
    "Green Consumer Goods",
    "GreenTech",
    "Grocery",
    "Group Buying",
    "Guides",
    "Handmade",
    "Hardware",
    "Health Care",
    "Health Diagnostics",
    "Health Insurance",
    "Hedge Funds",
    "Higher Education",
    "Hockey",
    "Home and Garden",
    "Home Decor",
    "Home Health Care",
    "Home Improvement",
    "Home Renovation",
    "Home Services",
    "Homeland Security",
    "Homeless Shelter",
    "Horticulture",
    "Hospital",
    "Hospitality",
    "Hotel",
    "Housekeeping Service",
    "Human Computer Interaction",
    "Human Resources",
    "Humanitarian",
    "Hunting",
    "Hydroponics",
    "IaaS",
    "Identity Management",
    "Image Recognition",
    "Impact Investing",
    "In-Flight Entertainment",
    "Incubators",
    "Independent Music",
    "Indoor Positioning",
    "Industrial",
    "Industrial Automation",
    "Industrial Design",
    "Industrial Engineering",
    "Industrial Manufacturing",
    "Information and Communications Technology (ICT)",
    "Information Services",
    "Information Technology",
    "Infrastructure",
    "Innovation Management",
    "Insurance",
    "InsurTech",
    "Intellectual Property",
    "Intelligent Systems",
    "Interior Design",
    "Internet",
    "Internet of Things",
    "Internet Radio",
    "Intrusion Detection",
    "iOS",
    "ISP",
    "IT Infrastructure",
    "IT Management",
    "Janitorial Service",
    "Jewelry",
    "Journalism",
    "Knowledge Management",
    "Landscaping",
    "Language Learning",
    "Laser",
    "Last Mile Transportation",
    "Laundry and Dry-cleaning",
    "Law Enforcement",
    "Lead Generation",
    "Lead Management",
    "Leasing",
    "Legal",
    "Legal Tech",
    "Leisure",
    "Lending",
    "LGBT",
    "Life Insurance",
    "Life Science",
    "Lifestyle",
    "Lighting",
    "Limousine Service",
    "Lingerie",
    "Linux",
    "Livestock",
    "Local",
    "Local Advertising",
    "Local Business",
    "Local Shopping",
    "Location Based Services",
    "Logistics",
    "Loyalty Programs",
    "Machine Learning",
    "Machinery Manufacturing",
    "macOS",
    "Made to Order",
    "Management Consulting",
    "Management Information Systems",
    "Manufacturing",
    "Mapping Services",
    "Marine Technology",
    "Marine Transportation",
    "Market Research",
    "Marketing",
    "Marketing Automation",
    "Marketplace",
    "Mechanical Design",
    "Mechanical Engineering",
    "Media and Entertainment",
    "Medical",
    "Medical Device",
    "Meeting Software",
    "Men's",
    "Messaging",
    "mHealth",
    "Micro Lending",
    "Military",
    "Millennials",
    "Mineral",
    "Mining",
    "Mining Technology",
    "MMO Games",
    "Mobile",
    "Mobile Advertising",
    "Mobile Apps",
    "Mobile Devices",
    "Mobile Payments",
    "MOOC",
    "Motion Capture",
    "Multi-level Marketing",
    "Museums and Historical Sites",
    "Music",
    "Music Education",
    "Music Label",
    "Music Streaming",
    "Music Venues",
    "Musical Instruments",
    "Nanotechnology",
    "National Security",
    "Natural Language Processing",
    "Natural Resources",
    "Navigation",
    "Network Hardware",
    "Network Security",
    "Neuroscience",
    "News",
    "NFC",
    "Nightclubs",
    "Nightlife",
    "Nintendo",
    "Non Profit",
    "Nuclear",
    "Nursing and Residential Care",
    "Nutraceutical",
    "Nutrition",
    "Office Administration",
    "Oil and Gas",
    "Online Auctions",
    "Online Forums",
    "Online Games",
    "Online Portals",
    "Open Source",
    "Operating Systems",
    "Optical Communication",
    "Organic",
    "Organic Food",
    "Outdoor Advertising",
    "Outdoors",
    "Outpatient Care",
    "Outsourcing",
    "PaaS",
    "Packaging Services",
    "Paper Manufacturing",
    "Parenting",
    "Parking",
    "Parks",
    "Payments",
    "PC Games",
    "Peer to Peer",
    "Penetration Testing",
    "Performing Arts",
    "Personal Branding",
    "Personal Development",
    "Personal Finance",
    "Personal Health",
    "Personalization",
    "Pet",
    "Pharmaceutical",
    "Photo Editing",
    "Photo Sharing",
    "Photography",
    "Physical Security",
    "Plastics and Rubber Manufacturing",
    "Playstation",
    "Podcast",
    "Point of Sale",
    "Politics",
    "Pollution Control",
    "Ports and Harbors",
    "Power Grid",
    "Precious Metals",
    "Prediction Markets",
    "Predictive Analytics",
    "Presentation Software",
    "Presentations",
    "Price Comparison",
    "Primary Education",
    "Printing",
    "Privacy",
    "Private Cloud",
    "Private Social Networking",
    "Procurement",
    "Product Design",
    "Product Management",
    "Product Research",
    "Product Search",
    "Productivity Tools",
    "Professional Networking",
    "Professional Services",
    "Project Management",
    "Property Development",
    "Property Insurance",
    "Property Management",
    "Psychology",
    "Public Relations",
    "Public Safety",
    "Public Transportation",
    "Publishing",
    "Q&A",
    "QR Codes",
    "Quality Assurance",
    "Quantified Self",
    "Quantum Computing",
    "Racing",
    "Railroad",
    "Reading Apps",
    "Real Estate",
    "Real Estate Investment",
    "Real Time",
    "Recipes",
    "Recreation",
    "Recreational Vehicles",
    "Recruiting",
    "Recycling",
    "Rehabilitation",
    "Religion",
    "Renewable Energy",
    "Rental",
    "Rental Property",
    "Reputation",
    "Reservations",
    "Residential",
    "Resorts",
    "Restaurants",
    "Retail",
    "Retail Technology",
    "Retirement",
    "RFID",
    "Ride Sharing",
    "RISC",
    "Risk Management",
    "Robotics",
    "Roku",
    "Rugby",
    "SaaS",
    "Sailing",
    "Sales",
    "Sales Automation",
    "Same Day Delivery",
    "Satellite Communication",
    "Scheduling",
    "Seafood",
    "Search Engine",
    "Secondary Education",
    "Security",
    "Self-Storage",
    "SEM",
    "Semantic Search",
    "Semantic Web",
    "Semiconductor",
    "Sensor",
    "SEO",
    "Serious Games",
    "Service Industry",
    "Sex Industry",
    "Sex Tech",
    "Sharing Economy",
    "Shipping",
    "Shipping Broker",
    "Shoes",
    "Shopping",
    "Shopping Mall",
    "Simulation",
    "Skiing",
    "Skill Assessment",
    "Small and Medium Businesses",
    "Smart Building",
    "Smart Cities",
    "Smart Home",
    "SMS",
    "Snack Food",
    "SNS",
    "Soccer",
    "Social",
    "Social Assistance",
    "Social Bookmarking",
    "Social CRM",
    "Social Entrepreneurship",
    "Social Impact",
    "Social Media",
    "Social Media Advertising",
    "Social Media Management",
    "Social Media Marketing",
    "Social Network",
    "Social News",
    "Social Recruiting",
    "Social Shopping",
    "Software",
    "Software Engineering",
    "Solar",
    "Space Travel",
    "Spam Filtering",
    "Speech Recognition",
    "Sponsorship",
    "Sporting Goods",
    "Sports",
    "Staffing Agency",
    "STEM Education",
    "Stock Exchanges",
    "Subscription Service",
    "Supply Chain Management",
    "Surfing",
    "Sustainability",
    "Swimming",
    "Table Tennis",
    "Task Management",
    "Taxi Service",
    "Tea",
    "Technical Support",
    "Teenagers",
    "Telecommunications",
    "Tennis",
    "Test and Measurement",
    "Text Analytics",
    "Textbook",
    "Textiles",
    "Theatre",
    "Therapeutics",
    "Ticketing",
    "Timber",
    "Timeshare",
    "Tizen",
    "Tobacco",
    "Tour Operator",
    "Tourism",
    "Toys",
    "Trade Shows",
    "Trading Platform",
    "Training",
    "Transaction Processing",
    "Translation Service",
    "Transportation",
    "Travel",
    "Travel Accommodations",
    "Travel Agency",
    "Tutoring",
    "TV",
    "TV Production",
    "Twitter",
    "Ultimate Frisbee",
    "Underserved Children",
    "Unified Communications",
    "Universities",
    "Usability Testing",
    "UX Design",
    "Vacation Rental",
    "Vending and Concessions",
    "Venture Capital",
    "Vertical Search",
    "Veterinary",
    "Video",
    "Video Advertising",
    "Video Chat",
    "Video Conferencing",
    "Video Editing",
    "Video Games",
    "Video on Demand",
    "Video Streaming",
    "Virtual Assistant",
    "Virtual Currency",
    "Virtual Desktop",
    "Virtual Goods",
    "Virtual Reality",
    "Virtual Workforce",
    "Virtual World",
    "Virtualization",
    "Visual Search",
    "Vocational Education",
    "VoIP",
    "Volley Ball",
    "Warehousing",
    "Waste Management",
    "Water",
    "Water Purification",
    "Water Transportation",
    "Wealth Management",
    "Wearables",
    "Web Apps",
    "Web Browsers",
    "Web Design",
    "Web Development",
    "Web Hosting",
    "WebOS",
    "Wedding",
    "Wellness",
    "Wholesale",
    "Wind Energy",
    "Windows",
    "Windows Phone",
    "Wine And Spirits",
    "Winery",
    "Wired Telecommunications",
    "Wireless",
    "Women's",
    "Wood Processing",
    "Xbox",
    "Young Adults",
];

export const POSITION_JOB_FUNCTIONS: string[] = [
    "Accounting",
    "Accounting/Auditing",
    "Administration",
    "Administrative",
    "Advertising",
    "Analyst",
    "Art/Creative",
    "Business Development",
    "Communications",
    "Consulting",
    "Customer Service",
    "Data Science",
    "Design",
    "Distribution",
    "Education",
    "Engineering",
    "Finance",
    "General Business",
    "HR",
    "Health Care Provider",
    "Human Resources",
    "IT",
    "Information Technology",
    "Legal",
    "Management",
    "Manufacturing",
    "Marketing",
    "Operations",
    "Other",
    "Other Engineering",
    "People",
    "Product",
    "Product Management",
    "Production",
    "Project Management",
    "Public Relations",
    "Purchasing",
    "Quality Assurance",
    "Research",
    "Sales",
    "Science",
    "Software Engineering",
    "Strategy/Planning",
    "Supply Chain",
    "Training",
    "Writing/Editing",
];

export const POSITION_INDUSTRIES: string[] = [
    "Accessible Architecture",
    "Accounting",
    "Administration of Justice",
    "Administrative and Support Services",
    "Advertising Services",
    "Agricultural Chemical Manufacturing",
    "Agriculture, Construction, Mining Machinery Manufacturing",
    "Air, Water, and Waste Program Management",
    "Airlines and Aviation",
    "Alternative Dispute Resolution",
    "Alternative Medicine",
    "Ambulance Services",
    "Amusement Parks and Arcades",
    "Animal Feed Manufacturing",
    "Animation",
    "Animation and Post-production",
    "Apparel & Fashion",
    "Apparel Manufacturing",
    "Appliances, Electrical, and Electronics Manufacturing",
    "Architectural and Structural Metal Manufacturing",
    "Architecture and Planning",
    "Armed Forces",
    "Artists and Writers",
    "Arts & Crafts",
    "Audio and Video Equipment Manufacturing",
    "Automation Machinery Manufacturing",
    "Automotive",
    "Aviation & Aerospace",
    "Aviation and Aerospace Component Manufacturing",
    "Banking",
    "Bars, Taverns, and Nightclubs",
    "Beverage Manufacturing",
    "Biotechnology",
    "Biotechnology Research",
    "Blockchain Services",
    "Boilers, Tanks, and Shipping Container Manufacturing",
    "Book",
    "Book Publishing",
    "Book and Periodical Publishing",
    "Broadcast Media Production and Distribution",
    "Building Construction",
    "Building Equipment Contractors",
    "Building Materials",
    "Building Structure and Exterior Contractors",
    "Business Consulting and Services",
    "Business Content",
    "Business Intelligence Platforms",
    "Business Supplies & Equipment",
    "Capital Markets",
    "Caterers",
    "Chemical Manufacturing",
    "Chemical Raw Materials Manufacturing",
    "Child Day Care Services",
    "Civic and Social Organizations",
    "Civil Engineering",
    "Climate Technology Product Manufacturing",
    "Coal Mining",
    "Collection Agencies",
    "Commercial Real Estate",
    "Commercial and Industrial Equipment Rental",
    "Commercial and Industrial Machinery Maintenance",
    "Commercial and Service Industry Machinery Manufacturing",
    "Communications Equipment Manufacturing",
    "Community Services",
    "Computer Games",
    "Computer Hardware",
    "Computer Hardware Manufacturing",
    "Computer Networking",
    "Computer Networking Products",
    "Computer and Network Security",
    "Computers and Electronics Manufacturing",
    "Construction",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Goods Rental",
    "Consumer Services",
    "Correctional Institutions",
    "Cosmetics",
    "Courts of Law",
    "Dairy",
    "Dairy Product Manufacturing",
    "Data Infrastructure and Analytics",
    "Data Security Software Products",
    "Defense & Space",
    "Defense and Space Manufacturing",
    "Dentists",
    "Design",
    "Design Services",
    "Desktop Computing Software Products",
    "E-Learning Providers",
    "E-learning",
    "Economic Programs",
    "Education",
    "Education Administration Programs",
    "Education Management",
    "Electric Lighting Equipment Manufacturing",
    "Electric Power Generation",
    "Electric Power Transmission, Control, and Distribution",
    "Electrical Equipment Manufacturing",
    "Electronic and Precision Equipment Maintenance",
    "Embedded Software Products",
    "Emergency and Relief Services",
    "Engineering Services",
    "Engines and Power Transmission Equipment Manufacturing",
    "Entertainment",
    "Entertainment Providers",
    "Environmental Services",
    "Equipment Rental Services",
    "Events Services",
    "Executive Offices",
    "Executive Search Services",
    "Fabricated Metal Products",
    "Facilities Services",
    "Farming",
    "Fashion Accessories Manufacturing",
    "Financial Services",
    "Fine Art",
    "Fire Protection",
    "Fisheries",
    "Food",
    "Food & Beverages",
    "Food Production",
    "Food and Beverage Manufacturing",
    "Food and Beverage Retail",
    "Food and Beverage Services",
    "Freight and Package Transportation",
    "Fundraising",
    "Furniture",
    "Furniture and Home Furnishings Manufacturing",
    "Gambling Facilities and Casinos",
    "Gas",
    "Glass Product Manufacturing",
    "Glass, Ceramics and Concrete Manufacturing",
    "Golf Courses and Country Clubs",
    "Government Administration",
    "Government Relations",
    "Government Relations Services",
    "Graphic Design",
    "Ground Passenger Transportation",
    "HVAC and Refrigeration Equipment Manufacturing",
    "Health and Human Services",
    "Health, Wellness & Fitness",
    "Higher Education",
    "Highway, Street, and Bridge Construction",
    "Holding Companies",
    "Home Health Care Services",
    "Horticulture",
    "Hospitality",
    "Hospitals",
    "Hospitals and Health Care",
    "Hospitals, Temporary Help Services",
    "Hotels and Motels",
    "Household Appliance Manufacturing",
    "Household Services",
    "Housing Programs",
    "Housing and Community Development",
    "Human Resources",
    "Human Resources Services",
    "IT Services and IT Consulting",
    "IT System Custom Software Development",
    "IT System Data Services",
    "IT System Operations and Maintenance",
    "IT System Training and Support",
    "Import & Export",
    "Individual and Family Services",
    "Industrial Automation",
    "Industrial Machinery Manufacturing",
    "Industry Associations",
    "Information Services",
    "Information Technology & Services",
    "Insurance",
    "Insurance Agencies and Brokerages",
    "Insurance Carriers",
    "Interior Design",
    "International Affairs",
    "International Trade and Development",
    "Internet Marketplace Platforms",
    "Internet News",
    "Internet Publishing",
    "Investment Advice",
    "Investment Banking",
    "Investment Management",
    "Janitorial Services",
    "Landscaping Services",
    "Law Enforcement",
    "Law Practice",
    "Leasing Non-residential Real Estate",
    "Leasing Residential Real Estate",
    "Legal Services",
    "Legislative Offices",
    "Leisure, Travel & Tourism",
    "Libraries",
    "Loan Brokers",
    "Luxury Goods & Jewelry",
    "Machinery Manufacturing",
    "Manufacturing",
    "Maritime",
    "Maritime Transportation",
    "Market Research",
    "Marketing Services",
    "Measuring and Control Instrument Manufacturing",
    "Mechanical Or Industrial Engineering",
    "Media",
    "Media Production",
    "Medical Device",
    "Medical Equipment Manufacturing",
    "Medical Practices",
    "Medical and Diagnostic Laboratories",
    "Mental Health Care",
    "Metal Ore Mining",
    "Metal Treatments",
    "Metalworking Machinery Manufacturing",
    "Military",
    "Mining",
    "Mobile Computing Software Products",
    "Mobile Food Services",
    "Mobile Gaming Apps",
    "Motor Vehicle Manufacturing",
    "Motor Vehicle Parts Manufacturing",
    "Movies and Sound Recording",
    "Movies, Videos, and Sound",
    "Museums, Historical Sites, and Zoos",
    "Music",
    "Musicians",
    "Nanotechnology Research",
    "Natural Gas Distribution",
    "Newspaper Publishing",
    "Non-profit Organization Management",
    "Non-profit Organizations",
    "Nonresidential Building Construction",
    "Nuclear Electric Power Generation",
    "Nursing Homes and Residential Care Facilities",
    "Office Administration",
    "Office Furniture and Fixtures Manufacturing",
    "Oil",
    "Oil and Gas",
    "Online Audio and Video Media",
    "Online Media",
    "Online and Mail Order Retail",
    "Operations Consulting",
    "Outpatient Care Centers",
    "Outsourcing and Offshoring Consulting",
    "Outsourcing/Offshoring",
    "Packaging & Containers",
    "Packaging and Containers Manufacturing",
    "Paint, Coating, and Adhesive Manufacturing",
    "Paper & Forest Products",
    "Paper and Forest Product Manufacturing",
    "Performing Arts",
    "Periodical Publishing",
    "Personal Care Product Manufacturing",
    "Personal Care Services",
    "Pet Services",
    "Pharmaceutical Manufacturing",
    "Philanthropic Fundraising Services",
    "Photography",
    "Physical, Occupational and Speech Therapists",
    "Physicians",
    "Plastics Manufacturing",
    "Political Organizations",
    "Postal Services",
    "Primary Metal Manufacturing",
    "Primary and Secondary Education",
    "Printing Services",
    "Professional Services",
    "Professional Training and Coaching",
    "Program Development",
    "Public Health",
    "Public Policy",
    "Public Policy Offices",
    "Public Relations and Communications Services",
    "Public Safety",
    "Radio and Television Broadcasting",
    "Rail Transportation",
    "Railroad Equipment Manufacturing",
    "Ranching",
    "Real Estate",
    "Real Estate Agents and Brokers",
    "Recreational Facilities",
    "Religious Institutions",
    "Renewable Energy Equipment Manufacturing",
    "Renewable Energy Power Generation",
    "Renewable Energy Semiconductor Manufacturing",
    "Renewables & Environment",
    "Repair and Maintenance",
    "Research",
    "Research Services",
    "Residential Building Construction",
    "Restaurants",
    "Retail",
    "Retail Apparel and Fashion",
    "Retail Appliances, Electrical, and Electronic Equipment",
    "Retail Art Supplies",
    "Retail Building Materials and Garden Equipment",
    "Retail Furniture and Home Furnishings",
    "Retail Groceries",
    "Retail Health and Personal Care Products",
    "Retail Luxury Goods and Jewelry",
    "Retail Motor Vehicles",
    "Retail Musical Instruments",
    "Retail Office Equipment",
    "Retail Office Supplies and Gifts",
    "Retail Recyclable Materials & Used Merchandise",
    "Robot Manufacturing",
    "Robotics Engineering",
    "Rubber Products Manufacturing",
    "School and Employee Bus Services",
    "Security Guards and Patrol Services",
    "Security Systems Services",
    "Security and Investigations",
    "Semiconductor Manufacturing",
    "Semiconductors",
    "Services for Renewable Energy",
    "Services for the Elderly and Disabled",
    "Shipbuilding",
    "Shuttles and Special Needs Transportation Services",
    "Sightseeing Transportation",
    "Social Networking Platforms",
    "Software Development",
    "Solar Electric Power Generation",
    "Space Research and Technology",
    "Specialty Trade Contractors",
    "Spectator Sports",
    "Sporting Goods",
    "Sporting Goods Manufacturing",
    "Sports Teams and Clubs",
    "Staffing and Recruiting",
    "Strategic Management Services",
    "Surveying and Mapping Services",
    "Technical and Vocational Training",
    "Technology, Information",
    "Technology, Information and Internet",
    "Telecommunications",
    "Telephone Call Centers",
    "Textile Manufacturing",
    "Think Tanks",
    "Tobacco",
    "Tobacco Manufacturing",
    "Translation and Localization",
    "Transportation Equipment Manufacturing",
    "Transportation Programs",
    "Transportation, Logistics, Supply Chain and Storage",
    "Transportation/Trucking/Railroad",
    "Travel Arrangements",
    "Truck Transportation",
    "Turned Products and Fastener Manufacturing",
    "Urban Transit Services",
    "Utilities",
    "Utility System Construction",
    "Vehicle Repair and Maintenance",
    "Venture Capital and Private Equity Principals",
    "Veterinary",
    "Veterinary Services",
    "Warehousing",
    "Warehousing and Storage",
    "Waste Collection",
    "Water, Waste, Steam, and Air Conditioning Services",
    "Wellness and Fitness Services",
    "Wholesale",
    "Wholesale Appliances, Electrical, and Electronics",
    "Wholesale Building Materials",
    "Wholesale Chemical and Allied Products",
    "Wholesale Drugs and Sundries",
    "Wholesale Food and Beverage",
    "Wholesale Footwear",
    "Wholesale Furniture and Home Furnishings",
    "Wholesale Hardware, Plumbing, Heating Equipment",
    "Wholesale Import and Export",
    "Wholesale Metals and Minerals",
    "Wholesale Motor Vehicles and Parts",
    "Wholesale Recyclable Materials",
    "Wine & Spirits",
    "Wineries",
    "Wireless Services",
    "Wood Product Manufacturing",
    "Writing and Editing",
    "Zoos and Botanical Gardens",
];
